use clap::{Args, Parser, Subcommand, ValueEnum};
use std::path::PathBuf;

const AFTER_HELP: &str = "\
Examples:
  cargo compatible scan --workspace
  cargo compatible scan --package my-crate --format json
  cargo compatible resolve --rust-version 1.70
  cargo compatible resolve --write-candidate .cargo-compatible/candidate/Cargo.lock
  cargo compatible apply-lock --candidate-lockfile .cargo-compatible/candidate/Cargo.lock
  cargo compatible suggest-manifest --package my-crate
  cargo compatible explain serde";

const SCAN_AFTER_HELP: &str = "\
Examples:
  cargo compatible scan --workspace
  cargo compatible scan --package app --format json
  cargo compatible scan --manifest-path path/to/Cargo.toml --rust-version 1.70";

const RESOLVE_AFTER_HELP: &str = "\
Examples:
  cargo compatible resolve --workspace
  cargo compatible resolve --write-candidate .cargo-compatible/candidate/Cargo.lock
  cargo compatible resolve --write-report report.md --format markdown";

const APPLY_LOCK_AFTER_HELP: &str = "\
Examples:
  cargo compatible apply-lock --candidate-lockfile .cargo-compatible/candidate/Cargo.lock
  cargo compatible apply-lock --manifest-path path/to/Cargo.toml --candidate-lockfile candidate/Cargo.lock";

const SUGGEST_MANIFEST_AFTER_HELP: &str = "\
Examples:
  cargo compatible suggest-manifest --package app
  cargo compatible suggest-manifest --package app --write-manifests
  cargo compatible suggest-manifest --package app --allow-major --format json";

const EXPLAIN_AFTER_HELP: &str = "\
Examples:
  cargo compatible explain serde
  cargo compatible explain serde@1.0.218 --workspace
  cargo compatible explain 'serde 1.0.218 (registry+https://github.com/rust-lang/crates.io-index)'";

#[derive(Parser, Debug)]
#[command(
    name = "cargo-compatible",
    bin_name = "cargo compatible",
    version,
    about = "Audit a workspace's resolved dependency graph against a target Rust version or MSRV",
    after_help = AFTER_HELP
)]
pub struct Cli {
    #[command(subcommand)]
    pub command: Commands,
}

#[derive(Subcommand, Debug)]
pub enum Commands {
    Scan(ScanCommand),
    Resolve(ResolveCommand),
    ApplyLock(ApplyLockCommand),
    SuggestManifest(SuggestManifestCommand),
    Explain(ExplainCommand),
}

#[derive(Copy, Clone, Debug, Eq, PartialEq, ValueEnum)]
pub enum OutputFormat {
    Human,
    Json,
    Markdown,
}

#[derive(Args, Debug, Clone)]
pub struct SelectionArgs {
    #[arg(long, help = "Path to the workspace or package Cargo.toml to analyze")]
    pub manifest_path: Option<PathBuf>,
    #[arg(
        long,
        help = "Override the target Rust version instead of using selected members' rust-version"
    )]
    pub rust_version: Option<String>,
    #[arg(
        long,
        help = "Analyze all workspace members instead of only the root package"
    )]
    pub workspace: bool,
    #[arg(
        long = "package",
        short = 'p',
        help = "Select workspace members by exact package name, package ID, or manifest path"
    )]
    pub package: Vec<String>,
}

#[derive(Args, Debug)]
#[command(
    about = "Analyze the current resolved dependency graph without changing files",
    after_help = SCAN_AFTER_HELP
)]
pub struct ScanCommand {
    #[command(flatten)]
    pub selection: SelectionArgs,
    #[arg(
        long,
        value_enum,
        default_value = "human",
        help = "Render the report as human, json, or markdown"
    )]
    pub format: OutputFormat,
}

#[derive(Args, Debug, Clone)]
#[command(
    about = "Resolve a candidate lockfile in a temporary workspace copy",
    after_help = RESOLVE_AFTER_HELP
)]
pub struct ResolveCommand {
    #[command(flatten)]
    pub selection: SelectionArgs,
    #[arg(
        long,
        value_enum,
        default_value = "human",
        help = "Render the report as human, json, or markdown"
    )]
    pub format: OutputFormat,
    #[arg(
        long = "write-candidate",
        help = "Write the candidate Cargo.lock to this path without mutating the real workspace"
    )]
    pub write_candidate: Option<PathBuf>,
    #[arg(
        long,
        help = "Write the rendered resolve report using the selected --format"
    )]
    pub write_report: Option<PathBuf>,
}

#[derive(Args, Debug)]
#[command(
    about = "Apply a previously generated candidate lockfile to the real workspace",
    after_help = APPLY_LOCK_AFTER_HELP
)]
pub struct ApplyLockCommand {
    #[arg(long, help = "Path to the workspace or package Cargo.toml to update")]
    pub manifest_path: Option<PathBuf>,
    #[arg(
        long,
        help = "Path to a candidate Cargo.lock generated by `cargo compatible resolve --write-candidate`"
    )]
    pub candidate_lockfile: Option<PathBuf>,
}

#[derive(Args, Debug)]
#[command(
    about = "Suggest conservative direct dependency requirement changes",
    after_help = SUGGEST_MANIFEST_AFTER_HELP
)]
pub struct SuggestManifestCommand {
    #[command(flatten)]
    pub selection: SelectionArgs,
    #[arg(
        long,
        help = "Allow major-version suggestions when no compatible same-major candidate exists"
    )]
    pub allow_major: bool,
    #[arg(
        long,
        help = "Persist validated manifest edits instead of printing dry-run suggestions"
    )]
    pub write_manifests: bool,
    #[arg(
        long,
        value_enum,
        default_value = "human",
        help = "Render the report as human, json, or markdown"
    )]
    pub format: OutputFormat,
}

#[derive(Args, Debug)]
#[command(
    about = "Explain why a package is present and whether it blocks compatibility",
    after_help = EXPLAIN_AFTER_HELP
)]
pub struct ExplainCommand {
    #[command(flatten)]
    pub selection: SelectionArgs,
    #[arg(
        value_name = "CRATE-OR-PKGID",
        help = "Package name, name@version, or exact package ID within the selected dependency graph"
    )]
    pub query: String,
    #[arg(
        long,
        value_enum,
        default_value = "human",
        help = "Render the report as human, json, or markdown"
    )]
    pub format: OutputFormat,
}
