name: CI

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny,cargo-nextest
      - uses: Swatinem/rust-cache@v2
      - name: cargo fmt --check
        run: cargo fmt --check
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: cargo deny check
        run: cargo deny check
      - name: cargo nextest run
        run: cargo nextest run
      - name: cargo bench --no-run
        run: cargo bench --bench large_workspace_resolver --no-run
